# adapted from https://github.com/purescript-contrib/purescript-argonaut-generic/blob/d211820cfec5c7cf2caa20dc6dc293671949b55c/.github/workflows/ci.yml
name: Purescript example

on:
  push:
    branches:
      - "**"
    paths-ignore: []
  pull_request:
    paths-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with: # https://github.com/purescript-contrib/setup-purescript#specify-versions
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: spago install

      - name: Build source
        run: spago build --no-install

      - name: Run tests
        run: spago test --no-install

      - name: Verify formatting
        run: purs-tidy check src test
